export const EVENTS = [
    {
        id: 1,
        title: "Velonx Hackathon 2025",
        date: "2025-01-15",
        type: "Online",
        seats: 50,
        filled: 30,
        image: "/images/hackathon.jpg",
    },
    {
        id: 2,
        title: "AI & ML Workshop",
        date: "2025-02-01",
        type: "Offline",
        seats: 200,
        filled: 150,
        image: "/images/ai-workshop.jpg",
    },
    {
        id: 3,
        title: "Web3 Fundamentals Bootcamp",
        date: "2025-02-15",
        type: "Online",
        seats: 100,
        filled: 45,
        image: "/images/web3.jpg",
    },
    {
        id: 4,
        title: "DSA Sprint Challenge",
        date: "2025-03-01",
        type: "Online",
        seats: 300,
        filled: 120,
        image: "/images/dsa.jpg",
    },
];

export const PROJECTS = [
    {
        id: 1,
        title: "Smart Campus App",
        description: "A mobile app to navigate campus and track attendance using QR codes.",
        stack: ["React Native", "Firebase", "Node.js"],
        status: "Completed",
        outcome: "Deployed to App Store with 500+ downloads",
        github: "https://github.com/velonx/smart-campus",
    },
    {
        id: 2,
        title: "EcoTracker",
        description: "IoT based waste management system for smart cities.",
        stack: ["Arduino", "Python", "React", "MongoDB"],
        status: "Running",
        members: ["Alice", "Bob", "Charlie"],
        deadline: "2025-03-30",
    },
    {
        id: 3,
        title: "AI Resume Analyzer",
        description: "ML-powered tool to analyze and score resumes against job descriptions.",
        stack: ["Python", "FastAPI", "React", "OpenAI"],
        status: "Running",
        members: ["David", "Eve"],
        deadline: "2025-04-15",
    },
    {
        id: 4,
        title: "Community Forum",
        description: "A discussion platform for tech enthusiasts with gamification features.",
        stack: ["Next.js", "PostgreSQL", "Prisma"],
        status: "Completed",
        outcome: "Active community with 2000+ posts",
        github: "https://github.com/velonx/forum",
    },
];

export const MENTORS = [
    {
        id: 1,
        name: "Dr. Smith",
        expertise: ["Artificial Intelligence", "Machine Learning", "Python"],
        company: "Google",
        bio: "10+ years in ML research",
        rating: 4.9,
        sessions: 120,
    },
    {
        id: 2,
        name: "Jane Doe",
        expertise: ["React", "Node.js", "TypeScript"],
        company: "Meta",
        bio: "Senior Engineer, open source contributor",
        rating: 4.8,
        sessions: 85,
    },
    {
        id: 3,
        name: "Alex Chen",
        expertise: ["AWS", "Cloud Architecture", "DevOps"],
        company: "AWS",
        bio: "Solutions Architect, AWS certified",
        rating: 4.7,
        sessions: 64,
    },
    {
        id: 4,
        name: "Priya Sharma",
        expertise: ["Data Science", "Python", "Statistics"],
        company: "Microsoft",
        bio: "Data Science Lead, PhD in Statistics",
        rating: 4.9,
        sessions: 92,
    },
    {
        id: 5,
        name: "Marcus Johnson",
        expertise: ["Mobile Development", "Flutter", "Swift"],
        company: "Apple",
        bio: "iOS Lead, 8+ years mobile experience",
        rating: 4.6,
        sessions: 45,
    },
    {
        id: 6,
        name: "Sarah Williams",
        expertise: ["UI/UX Design", "Figma", "Product Design"],
        company: "Airbnb",
        bio: "Design Lead, former design agency founder",
        rating: 4.8,
        sessions: 78,
    },
];

export const LEADERBOARD = [
    { rank: 1, name: "Alice", xp: 2500, role: "Builder", avatar: "A", badge: "🏆", level: 12, projects: 8 },
    { rank: 2, name: "Bob", xp: 2350, role: "Contributor", avatar: "B", badge: "🥈", level: 11, projects: 6 },
    { rank: 3, name: "Charlie", xp: 2100, role: "Speedster", avatar: "C", badge: "🥉", level: 10, projects: 5 },
    { rank: 4, name: "David", xp: 1950, role: "Builder", avatar: "D", badge: "⭐", level: 9, projects: 7 },
    { rank: 5, name: "Eve", xp: 1800, role: "Mentor", avatar: "E", badge: "🌟", level: 9, projects: 4 },
    { rank: 6, name: "Frank", xp: 1650, role: "Contributor", avatar: "F", badge: "💫", level: 8, projects: 5 },
    { rank: 7, name: "Grace", xp: 1500, role: "Builder", avatar: "G", badge: "✨", level: 7, projects: 4 },
    { rank: 8, name: "Henry", xp: 1350, role: "Speedster", avatar: "H", badge: "🔥", level: 6, projects: 3 },
];

export const RESOURCES = [
    { id: 1, category: "Web Development", items: 24, icon: "code" },
    { id: 2, category: "Data Structures", items: 36, icon: "tree" },
    { id: 3, category: "Machine Learning", items: 18, icon: "brain" },
    { id: 4, category: "Cybersecurity", items: 12, icon: "shield" },
    { id: 5, category: "Mobile Development", items: 15, icon: "smartphone" },
    { id: 6, category: "DevOps", items: 20, icon: "server" },
];

// Scheduled Meetings for Calendar
export const SCHEDULED_MEETINGS = [
    {
        id: "mtg-1",
        title: "Web Development Bootcamp - Session 1",
        description: "Introduction to modern web development with React and Next.js",
        date: new Date(2025, 0, 11), // Jan 11, 2025
        time: "9:00 - 11:00 AM",
        timezone: "UTC",
        meetingLink: "https://meet.google.com/abc-defg-hij",
        platform: "google-meet" as const,
        type: "workshop" as const,
        status: "upcoming" as const,
        maxAttendees: 50,
        currentAttendees: 32,
        createdBy: "admin@velonx.com",
    },
    {
        id: "mtg-2",
        title: "AI/ML Study Group",
        description: "Weekly discussion on machine learning algorithms",
        date: new Date(2025, 0, 15), // Jan 15, 2025
        time: "3:00 - 5:00 PM",
        timezone: "UTC",
        meetingLink: "https://zoom.us/j/123456789",
        platform: "zoom" as const,
        type: "networking" as const,
        status: "upcoming" as const,
        maxAttendees: 30,
        currentAttendees: 18,
        createdBy: "admin@velonx.com",
    },
    {
        id: "mtg-3",
        title: "Hackathon Kickoff Meeting",
        description: "Official start of Velonx Hackathon 2025",
        date: new Date(2025, 0, 15), // Jan 15, 2025
        time: "10:00 AM - 12:00 PM",
        timezone: "UTC",
        meetingLink: "https://discord.gg/velonx-hack",
        platform: "discord" as const,
        type: "hackathon" as const,
        status: "upcoming" as const,
        maxAttendees: 100,
        currentAttendees: 67,
        createdBy: "admin@velonx.com",
    },
    {
        id: "mtg-4",
        title: "Project Showcase & Feedback",
        description: "Present your projects and get feedback from mentors",
        date: new Date(2025, 0, 18), // Jan 18, 2025
        time: "2:00 - 4:00 PM",
        timezone: "UTC",
        meetingLink: "https://teams.microsoft.com/meet/velonx-showcase",
        platform: "teams" as const,
        type: "workshop" as const,
        status: "upcoming" as const,
        maxAttendees: 40,
        currentAttendees: 25,
        createdBy: "admin@velonx.com",
    },
    {
        id: "mtg-5",
        title: "DSA Problem Solving Session",
        description: "Live coding session on data structures and algorithms",
        date: new Date(2025, 0, 22), // Jan 22, 2025
        time: "5:00 - 7:00 PM",
        timezone: "UTC",
        meetingLink: "https://meet.google.com/xyz-abcd-efg",
        platform: "google-meet" as const,
        type: "workshop" as const,
        status: "upcoming" as const,
        maxAttendees: 60,
        currentAttendees: 42,
        createdBy: "admin@velonx.com",
    },
    {
        id: "mtg-6",
        title: "Career Guidance Webinar",
        description: "Tips for landing your first tech job",
        date: new Date(2025, 0, 25), // Jan 25, 2025
        time: "6:00 - 8:00 PM",
        timezone: "UTC",
        meetingLink: "https://zoom.us/j/987654321",
        platform: "zoom" as const,
        type: "webinar" as const,
        status: "upcoming" as const,
        maxAttendees: 200,
        currentAttendees: 156,
        createdBy: "admin@velonx.com",
    },
];
